# Generated by Django 4.0.6 on 2022-07-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Songs',
        ),
    ]
